//caution do not edit this file manually it is a template in tenjin format
`define  Buff_size 32
////////////////////////////////////////////
module top(clk,rst_n,rs232_rx, BusA,BusB,BusC,BusD, led);

///////////////////////////////////////////
input clk;	// 50MHz
input rst_n;	//reset, neg edge.
input rs232_rx;	// RS232 rec
//output rs232_tx;	//	RS232 transfer
/////////////////////////////////////////

inout [17:2] BusA;
inout [51:26] BusB;
inout [82:70] BusC;
inout [92:92] BusD;


////////////////////////////////////////
output led; // debug led

// state control						
parameter IDLE = 3'b000;
parameter S1 = 3'b001;
parameter WAIT = 3'b010;
parameter SAVE = 3'b100;

// commond reg
parameter A=8'h41 ;
parameter B=8'h42 ;
parameter C=8'h43 ;
parameter D=8'h44 ;
parameter E=8'h45 ;
parameter F=8'h46 ;
parameter G=8'h47 ;
parameter H=8'h48 ;
parameter I=8'h49 ;
parameter J=8'h4a ;
parameter K=8'h4b ;
parameter L=8'h4c ;
parameter M=8'h4d ;
parameter N=8'h4e ;
parameter O=8'h4f ;
parameter P=8'h50 ;
parameter Q=8'h51 ;
parameter R=8'h52 ;
parameter S=8'h53 ;
parameter T=8'h54 ;
parameter U=8'h55 ;
parameter V=8'h56 ;
parameter W=8'h57 ;
parameter X=8'h58 ;
parameter Y=8'h59 ;
parameter Z=8'h5a ;
parameter Z0=8'h30 ;
parameter I1=8'h31 ;
parameter II=8'h32 ;
parameter III=8'h33 ;
parameter IV=8'h34 ;
parameter V5=8'h35 ;
parameter VI=8'h36 ;
parameter VII=8'h37 ;
parameter VIII=8'h38 ;
parameter VIIII=8'h39 ;

//definition of inputs/outputs
wire test;
wire Flag; // signal the uart has data
wire rs232_rx;
wire clk,rst_n;
wire bps_start;	// start receive
wire bps_start_t;	// start tranmit
wire clk_bps;	//  uart bps
wire clk_bps_t;	//  uart bps
wire[7:0] rx_data; // receive data to parser
wire rx_int;       // receive interrupt

wire rx_error;
wire tx_error;

wire rx_complete;
wire tx_complete;

 
wire compara_error_uart7bit;
wire compare_ok;
wire rs232_tx7to7;
wire rs232_rx7to7; 
    



////////////////////////////////////////////////////////////////////////////////////////////////
//debug led
reg led;
																			
// settings for log register
reg [`Buff_size-1:0] Buff_temp;
reg [`Buff_size-9:0] Rx_cmd;											
reg [2:0] Current, Next;		
reg Flag_temp;
//build in module enable
reg linkBIM;

reg linkFWM;
reg linkFDC;
reg linkLUT;
reg linkGLO;
reg linkFOC;
reg linkFSM;
reg linkUSH;

reg enable_uart7bit;
reg[2:0] uart_speed_set_7bit;
reg tx_start_f_7bit;
    reg linkFSP;
reg linkFSS;
reg linkFUT;
reg linkCMP;
reg linkFCP;
reg linkPMS;
reg linkUART;
reg linkSPI;
reg linkPMH;
reg linkEWM;
reg linkLPT;
reg linkPWT;
reg linkTRG;
reg linkFRL;
reg linkFPT;
reg linkFRT;
reg linkSHL;
reg linkGII;
reg linkARR;
reg linkFIC;
reg linkLPIT;
reg linkUSF;


assign BusA[15] =  linkFWM ? BusB[30] : 1'bz;
assign BusA[8] =  linkFWM ? BusB[30] : 1'bz;
assign BusB[38] =  linkFDC ? BusA[15] : 1'bz;
assign BusC[70] =  linkLUT ? BusB[49] : 1'bz;
assign BusB[48] =  linkLUT ? BusC[71] : 1'bz;
assign BusA[15] =  linkGLO ? BusA[2] : 1'bz;
assign BusA[8] =  linkGLO ? BusA[2] : 1'bz;
assign BusA[15] =  linkFOC ? BusA[2] : 1'bz;
assign BusA[8] =  linkFOC ? BusA[2] : 1'bz;
assign BusC[82] =  linkFSM ? BusB[26] : 1'bz;
assign BusC[78] =  linkFSM ? BusB[28] : 1'bz;
assign BusB[30] =  linkFSM ? BusC[77] : 1'bz;
assign BusC[76] =  linkFSM ? BusB[29] : 1'bz;
assign BusA[17] =  linkUSH ? compara_error_uart7bit : 1'bz;
assign rs232_rx7to7 =  linkUSH ? BusC[71] : 1'bz;
assign BusC[70] =  linkUSH ? rs232_tx7to7 : 1'bz;
assign BusA[15] =  linkFSP ? BusA[2] : 1'bz;
assign BusA[8] =  linkFSP ? BusA[2] : 1'bz;
assign BusB[26] =  linkFSS ? BusC[82] : 1'bz;
assign BusB[28] =  linkFSS ? BusC[78] : 1'bz;
assign BusC[76] =  linkFSS ? BusB[29] : 1'bz;
assign BusB[30] =  linkFSS ? BusC[77] : 1'bz;
assign BusB[26] =  linkFUT ? BusB[49] : 1'bz;
assign BusB[48] =  linkFUT ? BusB[30] : 1'bz;
assign BusB[50] =  linkCMP ? BusA[16] : 1'bz;
assign BusA[17] =  linkCMP ? BusA[3] : 1'bz;
assign BusA[15] =  linkFCP ? BusA[2] : 1'bz;
assign BusA[8] =  linkFCP ? BusA[2] : 1'bz;
assign BusB[35] =  linkPMS ? BusA[16] : 1'bz;
assign BusC[82] =  linkSPI ? BusB[26] : 1'bz;
assign BusC[78] =  linkSPI ? BusB[28] : 1'bz;
assign BusC[76] =  linkSPI ? BusB[29] : 1'bz;
assign BusB[30] =  linkSPI ? BusC[77] : 1'bz;
assign BusB[35] =  linkPMH ? BusA[16] : 1'bz;
assign BusB[35] =  linkEWM ? BusA[16] : 1'bz;
assign BusA[15] =  linkLPT ? BusA[2] : 1'bz;
assign BusA[8] =  linkLPT ? BusA[2] : 1'bz;
assign BusB[47] =  linkPWT ? BusA[15] : 1'bz;
assign BusA[15] =  linkTRG ? BusB[26] : 1'bz;
assign BusA[8] =  linkTRG ? BusB[26] : 1'bz;
assign BusB[26] =  linkFRL ? BusC[82] : 1'bz;
assign BusB[28] =  linkFRL ? BusC[78] : 1'bz;
assign BusB[30] =  linkFRL ? BusC[77] : 1'bz;
assign BusC[76] =  linkFRL ? BusB[29] : 1'bz;
assign BusA[15] =  linkFPT ? BusA[2] : 1'bz;
assign BusA[8] =  linkFPT ? BusA[2] : 1'bz;
assign BusB[35] =  linkFRT ? BusA[16] : 1'bz;
assign BusA[17] =  linkSHL ? BusD[92] : 1'bz;
assign BusB[35] =  linkGII ? BusA[16] : 1'bz;
assign BusA[17] =  linkGII ? BusA[2] : 1'bz;
assign BusB[51] =  linkARR ? BusA[16] : 1'bz;
assign BusB[40] =  linkFIC ? BusA[16] : 1'bz;
assign BusA[15] =  linkLPIT ? BusA[2] : 1'bz;
assign BusA[8] =  linkLPIT ? BusA[2] : 1'bz;
assign BusA[17] =  linkUSF ? BusA[4] : 1'bz;


 
uart_top7to7		uart_top7to7(
						.clk(clk),
						.rst_n(tx_start_f_7bit),
						.rs232_rx(rs232_rx7to7),
						.rs232_tx(rs232_tx7to7),
						.data_ok(compara_error_uart7bit),
						.uart_ctl(uart_speed_set_7bit)
						); 
     
speed_select    speed_select( .clk(clk),  //baudrate selection
                      .rst_n(rst_n),
                      .rx_enable(bps_start),
                      .tx_enable(bps_start_t),
                      .buad_clk_rx(clk_bps),
                      .buad_clk_tx(clk_bps_t)
                      );

my_uart_rx      my_uart_rx(   .rst_n(rst_n), 
                      .baud_clk(clk_bps), 
                      .uart_rx(rs232_rx), 
                      .rx_data(rx_data),
                      .rx_enable(bps_start), 
                      .rx_complete(rx_complete), 
                      .rx_error(rx_error)
                      );
                      
my_uart_tx      my_uart_tx(   .rst_n(capture_rst), 
                      .baud_clk(clk_bps_t), 
                      .tx_start(tx_start), 
                      .tx_data(tx_data), 
                      .tx_enable(bps_start_t), 
                      .tx_complete(tx_complete), 
                      .uart_tx(rs232_tx), 
                      .error(tx_error)
                      );
    

/////////////////////////////////////////////////////////////////////////////////////////////////////

reg flag_reg;
always @ (negedge bps_start or negedge rst_n)
begin
	if (!rst_n)
		flag_reg <= 1'b0;
	else if (!bps_start)
		flag_reg <= ~flag_reg;
end
assign Flag = flag_reg;

always @ (posedge clk or negedge rst_n)
begin
	if (!rst_n)
		Current <= IDLE;
	else
		Current <= Next;
end

// the state machine for receive data bytes
always @ (*)
begin
	Next = IDLE;
	case (Current)
		IDLE:
			if (rx_data == 8'h24) //$
				Next = S1;
			else
				Next = IDLE;
		S1:
			if (Flag_temp != Flag)
			begin
				if (rx_data != 8'h0d) //\n
					Next = S1;
				else
					Next = SAVE;
			end
			else
				Next = WAIT;
		WAIT:
			if (Flag_temp!=Flag)
			begin
				if (rx_data != 8'h0d)
					Next = S1;
				else
					Next = SAVE;
			end
			else
				Next = WAIT;
		default: Next = IDLE;
	endcase
end

always @ (posedge clk or negedge rst_n)
begin 
	if (!rst_n)
	begin
		Flag_temp <= 1'b0;
	end
	else
	begin
		Flag_temp <= Flag;
	end
end

always @ (posedge clk or negedge rst_n)
begin 
	if(!rst_n)
	begin
		Buff_temp <= `Buff_size'b0;
		Rx_cmd <= `Buff_size'b0;
	end
	else
	begin
		case (Current)	
			IDLE:  
			begin
				Buff_temp <= `Buff_size'b0;
			end
			S1:
			begin
				Buff_temp <= {{Buff_temp[`Buff_size - 9 : 0]}, rx_data};
			end 
			WAIT:
			begin
				Buff_temp <= Buff_temp;
			end 
			SAVE:
			begin
				Rx_cmd  <= Buff_temp[`Buff_size - 9 : 0];
				Buff_temp <= `Buff_size'b0;
			end
			default: 
			begin
			end
		endcase		
	end	
end

always @ (posedge clk or negedge rst_n)
begin
  if(!rst_n)
  begin
    //////////////////add link here////////////////
			linkFWM <= 1'b0;
			linkFDC <= 1'b0;
			linkLUT <= 1'b0;
			linkGLO <= 1'b0;
			linkFOC <= 1'b0;
			linkFSM <= 1'b0;
			linkUSH <= 1'b0;
			linkFSP <= 1'b0;
			linkFSS <= 1'b0;
			linkFUT <= 1'b0;
			linkCMP <= 1'b0;
			linkFCP <= 1'b0;
			linkPMS <= 1'b0;
			linkSPI <= 1'b0;
			linkPMH <= 1'b0;
			linkEWM <= 1'b0;
			linkLPT <= 1'b0;
			linkPWT <= 1'b0;
			linkTRG <= 1'b0;
			linkFRL <= 1'b0;
			linkFPT <= 1'b0;
			linkFRT <= 1'b0;
			linkSHL <= 1'b0;
			linkGII <= 1'b0;
			linkARR <= 1'b0;
			linkFIC <= 1'b0;
			linkLPIT <= 1'b0;
			linkUSF <= 1'b0;

    ///////////////////////////////////////////////
    led <= 1'b0; // for debug led
    linkBIM <= 1'b1;
  end
  else
  begin
    case(Rx_cmd)
    ///////////////////add case here/////////////
      			
      {F,W, M}: //{C,M,D}
      begin
        linkFWM <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,D, C}: //{C,M,D}
      begin
        linkFDC <= 1'b1;

        led <= 1'b1;
      end
      			
      {L,U, T}: //{C,M,D}
      begin
        linkLUT <= 1'b1;

        led <= 1'b1;
      end
      			
      {G,L, O}: //{C,M,D}
      begin
        linkGLO <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,O, C}: //{C,M,D}
      begin
        linkFOC <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,S, M}: //{C,M,D}
      begin
        linkFSM <= 1'b1;

        led <= 1'b1;
      end
      
      {U,S, H}: //{C,M,D}
      begin
        linkUSF <= 1'b0;
		  linkUSH <= 1'b1;
			 
          uart_speed_set_7bit <= 3'd4;
          tx_start_f_7bit <= 1'b1;
      

        led <= 1'b1;
      end
      			
      {F,S, P}: //{C,M,D}
      begin
        linkFSP <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,S, S}: //{C,M,D}
      begin
        linkFSS <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,U, T}: //{C,M,D}
      begin
        linkFUT <= 1'b1;

        led <= 1'b1;
      end
      			
      {C,M, P}: //{C,M,D}
      begin
        linkCMP <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,C, P}: //{C,M,D}
      begin
        linkFCP <= 1'b1;

        led <= 1'b1;
      end
      			
      {P,M, S}: //{C,M,D}
      begin
        linkPMS <= 1'b1;

        led <= 1'b1;
      end
      			
      {S,P, I}: //{C,M,D}
      begin
        linkSPI <= 1'b1;

        led <= 1'b1;
      end
      			
      {P,M, H}: //{C,M,D}
      begin
        linkPMH <= 1'b1;

        led <= 1'b1;
      end
      			
      {E,W, M}: //{C,M,D}
      begin
        linkEWM <= 1'b1;

        led <= 1'b1;
      end
      			
      {L,P, T}: //{C,M,D}
      begin
        linkLPT <= 1'b1;

        led <= 1'b1;
      end
      			
      {P,W, T}: //{C,M,D}
      begin
        linkPWT <= 1'b1;

        led <= 1'b1;
      end
      			
      {T,R, G}: //{C,M,D}
      begin
        linkTRG <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,R, L}: //{C,M,D}
      begin
        linkFRL <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,P, T}: //{C,M,D}
      begin
        linkFPT <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,R, T}: //{C,M,D}
      begin
        linkFRT <= 1'b1;

        led <= 1'b1;
      end
      			
      {S,H, L}: //{C,M,D}
      begin
        linkSHL <= 1'b1;

        led <= 1'b1;
      end
      			
      {G,I, I}: //{C,M,D}
      begin
        linkGII <= 1'b1;

        led <= 1'b1;
      end
      			
      {A,R, R}: //{C,M,D}
      begin
        linkARR <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,I, C}: //{C,M,D}
      begin
        linkFIC <= 1'b1;

        led <= 1'b1;
      end
      			
      {L,P, I}: //{C,M,D}
      begin
        linkLPIT <= 1'b1;

        led <= 1'b1;
      end
      			
      {U,S, F}: //{C,M,D}
      begin
        linkUSF <= 1'b1;

        led <= 1'b1;
      end
      
    /////////////////////////////////////////////

      {R,S,T}: //RESET
         begin
           			linkFWM <= 1'b0;
			linkFDC <= 1'b0;
			linkLUT <= 1'b0;
			linkGLO <= 1'b0;
			linkFOC <= 1'b0;
			linkFSM <= 1'b0;
			
    enable_uart7bit <= 1'b0;
    uart_speed_set_7bit<=3'd4;
    tx_start_f_7bit <= 1'b0;
    
			linkUSH <= 1'b0;
			linkFSP <= 1'b0;
			linkFSS <= 1'b0;
			linkFUT <= 1'b0;
			linkCMP <= 1'b0;
			linkFCP <= 1'b0;
			linkPMS <= 1'b0;
			linkSPI <= 1'b0;
			linkPMH <= 1'b0;
			linkEWM <= 1'b0;
			linkLPT <= 1'b0;
			linkPWT <= 1'b0;
			linkTRG <= 1'b0;
			linkFRL <= 1'b0;
			linkFPT <= 1'b0;
			linkFRT <= 1'b0;
			linkSHL <= 1'b0;
			linkGII <= 1'b0;
			linkARR <= 1'b0;
			linkFIC <= 1'b0;
			linkLPIT <= 1'b0;
			linkUSF <= 1'b0;

            led <= 1'b0;
            linkBIM <= 1'b1;
        end

         default:
         begin
          			linkFWM <= 1'b0;
			linkFDC <= 1'b0;
			linkLUT <= 1'b0;
			linkGLO <= 1'b0;
			linkFOC <= 1'b0;
			linkFSM <= 1'b0;
			
    enable_uart7bit <= 1'b0;
    uart_speed_set_7bit<=3'd4;
    enable_uart7bit <= 1'b0;
    
			linkUSH <= 1'b0;
			linkFSP <= 1'b0;
			linkFSS <= 1'b0;
			linkFUT <= 1'b0;
			linkCMP <= 1'b0;
			linkFCP <= 1'b0;
			linkPMS <= 1'b0;
			linkSPI <= 1'b0;
			linkPMH <= 1'b0;
			linkEWM <= 1'b0;
			linkLPT <= 1'b0;
			linkPWT <= 1'b0;
			linkTRG <= 1'b0;
			linkFRL <= 1'b0;
			linkFPT <= 1'b0;
			linkFRT <= 1'b0;
			linkSHL <= 1'b0;
			linkGII <= 1'b0;
			linkARR <= 1'b0;
			linkFIC <= 1'b0;
			linkLPIT <= 1'b0;
			linkUSF <= 1'b0;

          led <= 1'b0;
          linkBIM <= 1'b1;
      end
    endcase
  end
end


/////////////////////////////////////////////////////////////

endmodule
