//caution do not edit this file manually it is a template in tenjin format
`define  Buff_size 32
////////////////////////////////////////////
module top(clk,rst_n,rs232_rx, BusA,BusB,BusC,BusD, led);

///////////////////////////////////////////
input clk;	// 50MHz
input rst_n;	//reset, neg edge.
input rs232_rx;	// RS232 rec
//output rs232_tx;	//	RS232 transfer
/////////////////////////////////////////

inout [27:3] BusA;
inout [38:38] BusB;
inout [54:48] BusC;
inout [91:83] BusD;


////////////////////////////////////////
output led; // debug led

// state control						
parameter IDLE = 3'b000;
parameter S1 = 3'b001;
parameter WAIT = 3'b010;
parameter SAVE = 3'b100;

// commond reg
parameter A=8'h41 ;
parameter B=8'h42 ;
parameter C=8'h43 ;
parameter D=8'h44 ;
parameter E=8'h45 ;
parameter F=8'h46 ;
parameter G=8'h47 ;
parameter H=8'h48 ;
parameter I=8'h49 ;
parameter J=8'h4a ;
parameter K=8'h4b ;
parameter L=8'h4c ;
parameter M=8'h4d ;
parameter N=8'h4e ;
parameter O=8'h4f ;
parameter P=8'h50 ;
parameter Q=8'h51 ;
parameter R=8'h52 ;
parameter S=8'h53 ;
parameter T=8'h54 ;
parameter U=8'h55 ;
parameter V=8'h56 ;
parameter W=8'h57 ;
parameter X=8'h58 ;
parameter Y=8'h59 ;
parameter Z=8'h5a ;
parameter Z0=8'h30 ;
parameter I1=8'h31 ;
parameter II=8'h32 ;
parameter III=8'h33 ;
parameter IV=8'h34 ;
parameter V5=8'h35 ;
parameter VI=8'h36 ;
parameter VII=8'h37 ;
parameter VIII=8'h38 ;
parameter VIIII=8'h39 ;

//definition of inputs/outputs
wire test;
wire Flag; // signal the uart has data
wire rs232_rx;
wire clk,rst_n;
wire bps_start;	// start receive
wire bps_start_t;	// start tranmit
wire clk_bps;	//  uart bps
wire clk_bps_t;	//  uart bps
wire[7:0] rx_data; // receive data to parser
wire rx_int;       // receive interrupt

wire rx_error;
wire tx_error;

wire rx_complete;
wire tx_complete;


wire button_out_status;
          
wire ss_sck_b2b;
wire ss_mosi_b2b;
wire ss_miso_b2b;
wire ss_ssel_b2b;
wire spi_slave_result_b2b;
          
wire sm_sck;
wire sm_mosi;
wire sm_miso;
wire sm_cs_n;
wire spi_receive_status;
          



////////////////////////////////////////////////////////////////////////////////////////////////
//debug led
reg led;
																			
// settings for log register
reg [`Buff_size-1:0] Buff_temp;
reg [`Buff_size-9:0] Rx_cmd;											
reg [2:0] Current, Next;		
reg Flag_temp;
//build in module enable
reg linkBIM;

reg linkBTU;

reg  button_pull_done;
reg  button_rst_n;
    reg linkTDC;
reg linkSPS;
reg linkEMB;

reg spi_slave_rst_b2b;
    reg linkFPM;
reg linkTCW;
reg linkGLO;
reg linkDSS;

reg spi_tx_en;
reg spi_rx_en;
reg spi_rst;
reg mode_select_CPHA;
reg mode_select_CPOL;
    reg linkTCP;
reg linkSSM;
reg linkBTD;
reg linkTPT;
reg linkUART;
reg linkSSS;
reg linkTPW;
reg linkTOC;
reg linkFIU;
reg linkSPM;
reg linkTSP;
reg linkTIC;


assign BusA[5] =  linkBTU ? button_out_status : 1'bz;
assign BusC[48] =  linkTDC ? BusA[15] : 1'bz;
assign BusD[91] =  linkSPS ? BusA[21] : 1'bz;
assign BusD[83] =  linkSPS ? BusA[20] : 1'bz;
assign BusD[87] =  linkSPS ? BusA[19] : 1'bz;
assign BusA[18] =  linkSPS ? BusD[85] : 1'bz;
assign BusD[87] =  linkEMB ? ss_miso_b2b : 1'bz;
assign ss_mosi_b2b =  linkEMB ? BusD[85] : 1'bz;
assign ss_sck_b2b =  linkEMB ? BusD[91] : 1'bz;
assign ss_ssel_b2b =  linkEMB ? BusD[83] : 1'bz;
assign BusA[8] =  linkFPM ? BusA[5] : 1'bz;
assign BusA[15] =  linkFPM ? BusA[5] : 1'bz;
assign BusA[8] =  linkTCW ? BusC[48] : 1'bz;
assign BusA[15] =  linkTCW ? BusC[48] : 1'bz;
assign BusA[8] =  linkGLO ? BusB[38] : 1'bz;
assign BusA[15] =  linkGLO ? BusB[38] : 1'bz;
assign BusD[83] =  linkDSS ? sm_cs_n : 1'bz;
assign sm_miso =  linkDSS ? BusD[85] : 1'bz;
assign BusD[87] =  linkDSS ? sm_mosi : 1'bz;
assign BusD[91] =  linkDSS ? sm_sck : 1'bz;
assign BusA[8] =  linkTCP ? BusA[14] : 1'bz;
assign BusA[15] =  linkTCP ? BusA[14] : 1'bz;
assign BusD[83] =  linkSSM ? BusC[53] : 1'bz;
assign BusC[54] =  linkSSM ? BusD[85] : 1'bz;
assign BusD[87] =  linkSSM ? BusA[3] : 1'bz;
assign BusD[91] =  linkSSM ? BusA[5] : 1'bz;
assign BusA[5] =  linkBTD ? button_out_status : 1'bz;
assign BusA[8] =  linkTPT ? BusA[14] : 1'bz;
assign BusA[15] =  linkTPT ? BusA[14] : 1'bz;
assign BusC[53] =  linkSSS ? BusD[83] : 1'bz;
assign BusC[54] =  linkSSS ? BusD[85] : 1'bz;
assign BusD[87] =  linkSSS ? BusA[3] : 1'bz;
assign BusA[5] =  linkSSS ? BusD[91] : 1'bz;
assign BusA[8] =  linkTPW ? BusC[48] : 1'bz;
assign BusA[15] =  linkTPW ? BusC[48] : 1'bz;
assign BusA[8] =  linkTOC ? BusA[14] : 1'bz;
assign BusA[15] =  linkTOC ? BusA[14] : 1'bz;
assign BusA[3] =  linkFIU ? BusA[26] : 1'bz;
assign BusA[27] =  linkFIU ? BusA[5] : 1'bz;
assign BusA[21] =  linkSPM ? BusD[91] : 1'bz;
assign BusA[20] =  linkSPM ? BusD[83] : 1'bz;
assign BusD[87] =  linkSPM ? BusA[18] : 1'bz;
assign BusA[19] =  linkSPM ? BusD[85] : 1'bz;
assign BusA[8] =  linkTSP ? BusA[14] : 1'bz;
assign BusA[15] =  linkTSP ? BusA[14] : 1'bz;
assign BusA[14] =  linkTIC ? BusA[15] : 1'bz;



button_rst		button_rst_instance(
							.rst(button_rst_n),
							.clk(clk),
							.pull_done(button_pull_done),
							.out_status(button_out_status)
                            );

        
spi_slave_b2b		spi_slave_b2b_instance(
							.clk(clk),
							.sck(ss_sck_b2b),
							.mosi(ss_mosi_b2b),
							.miso(ss_miso_b2b),
							.ssel(ss_ssel_b2b),
							.rst_n(spi_slave_rst_b2b),
							.recived_status(spi_slave_result_b2b)
                            );

        
spi_ctrl      spi_ctrl_instance(
							.clk(clk),
							.rst_n(spi_rst),
							.sck(sm_sck),
							.mosi(sm_mosi),
							.miso(sm_miso),
							.cs_n(sm_cs_n),
							.spi_tx_en(spi_tx_en),
							.spi_rx_en(spi_rx_en),
							.mode_select_CPHA(mode_select_CPHA),
							.mode_select_CPOL(mode_select_CPOL),
							.receive_status(spi_receive_status)
							);
         
speed_select    speed_select( .clk(clk),  //baudrate selection
                      .rst_n(rst_n),
                      .rx_enable(bps_start),
                      .tx_enable(bps_start_t),
                      .buad_clk_rx(clk_bps),
                      .buad_clk_tx(clk_bps_t)
                      );

my_uart_rx      my_uart_rx(   .rst_n(rst_n), 
                      .baud_clk(clk_bps), 
                      .uart_rx(rs232_rx), 
                      .rx_data(rx_data),
                      .rx_enable(bps_start), 
                      .rx_complete(rx_complete), 
                      .rx_error(rx_error)
                      );
                      
my_uart_tx      my_uart_tx(   .rst_n(capture_rst), 
                      .baud_clk(clk_bps_t), 
                      .tx_start(tx_start), 
                      .tx_data(tx_data), 
                      .tx_enable(bps_start_t), 
                      .tx_complete(tx_complete), 
                      .uart_tx(rs232_tx), 
                      .error(tx_error)
                      );
    

/////////////////////////////////////////////////////////////////////////////////////////////////////

reg flag_reg;
always @ (negedge bps_start or negedge rst_n)
begin
	if (!rst_n)
		flag_reg <= 1'b0;
	else if (!bps_start)
		flag_reg <= ~flag_reg;
end
assign Flag = flag_reg;

always @ (posedge clk or negedge rst_n)
begin
	if (!rst_n)
		Current <= IDLE;
	else
		Current <= Next;
end

// the state machine for receive data bytes
always @ (*)
begin
	Next = IDLE;
	case (Current)
		IDLE:
			if (rx_data == 8'h24) //$
				Next = S1;
			else
				Next = IDLE;
		S1:
			if (Flag_temp != Flag)
			begin
				if (rx_data != 8'h0d) //\n
					Next = S1;
				else
					Next = SAVE;
			end
			else
				Next = WAIT;
		WAIT:
			if (Flag_temp!=Flag)
			begin
				if (rx_data != 8'h0d)
					Next = S1;
				else
					Next = SAVE;
			end
			else
				Next = WAIT;
		default: Next = IDLE;
	endcase
end

always @ (posedge clk or negedge rst_n)
begin 
	if (!rst_n)
	begin
		Flag_temp <= 1'b0;
	end
	else
	begin
		Flag_temp <= Flag;
	end
end

always @ (posedge clk or negedge rst_n)
begin 
	if(!rst_n)
	begin
		Buff_temp <= `Buff_size'b0;
		Rx_cmd <= `Buff_size'b0;
	end
	else
	begin
		case (Current)	
			IDLE:  
			begin
				Buff_temp <= `Buff_size'b0;
			end
			S1:
			begin
				Buff_temp <= {{Buff_temp[`Buff_size - 9 : 0]}, rx_data};
			end 
			WAIT:
			begin
				Buff_temp <= Buff_temp;
			end 
			SAVE:
			begin
				Rx_cmd  <= Buff_temp[`Buff_size - 9 : 0];
				Buff_temp <= `Buff_size'b0;
			end
			default: 
			begin
			end
		endcase		
	end	
end

always @ (posedge clk or negedge rst_n)
begin
  if(!rst_n)
  begin
    //////////////////add link here////////////////
			linkBTU <= 1'b0;
			linkTDC <= 1'b0;
			linkSPS <= 1'b0;
			linkEMB <= 1'b0;
			linkFPM <= 1'b0;
			linkTCW <= 1'b0;
			linkGLO <= 1'b0;
			linkDSS <= 1'b0;
			linkTCP <= 1'b0;
			linkSSM <= 1'b0;
			linkBTD <= 1'b0;
			linkTPT <= 1'b0;
			linkSSS <= 1'b0;
			linkTPW <= 1'b0;
			linkTOC <= 1'b0;
			linkFIU <= 1'b0;
			linkSPM <= 1'b0;
			linkTSP <= 1'b0;
			linkTIC <= 1'b0;

    ///////////////////////////////////////////////
    led <= 1'b0; // for debug led
    linkBIM <= 1'b1;
  end
  else
  begin
    case(Rx_cmd)
    ///////////////////add case here/////////////
      
      {B,T, U}: //{C,M,D}
      begin
        linkBTU <= 1'b1;
			 
        button_pull_done <= 1'b0;
		button_rst_n <= 1'b1;
        

        led <= 1'b1;
      end
      			
      {T,D, C}: //{C,M,D}
      begin
        linkTDC <= 1'b1;

        led <= 1'b1;
      end
      			
      {S,P, S}: //{C,M,D}
      begin
        linkSPS <= 1'b1;

        led <= 1'b1;
      end
      
      {E,M, B}: //{C,M,D}
      begin
        linkEMB <= 1'b1;
			 
        spi_slave_rst_b2b <= 1'b1;
        

        led <= 1'b1;
      end
      			
      {F,P, M}: //{C,M,D}
      begin
        linkFPM <= 1'b1;

        led <= 1'b1;
      end
      			
      {T,C, W}: //{C,M,D}
      begin
        linkTCW <= 1'b1;

        led <= 1'b1;
      end
      			
      {G,L, O}: //{C,M,D}
      begin
        linkGLO <= 1'b1;

        led <= 1'b1;
      end
      
      {D,S, S}: //{C,M,D}
      begin
        linkDSS <= 1'b1;
			 
        spi_rst <= 1'b1;
        spi_tx_en <= 1'b1;
        spi_rx_en <= 1'b1;
        mode_select_CPOL <= 1'b0;
        mode_select_CPHA <= 1'b0;	
        

        led <= 1'b1;
      end
      			
      {T,C, P}: //{C,M,D}
      begin
        linkTCP <= 1'b1;

        led <= 1'b1;
      end
      			
      {S,S, M}: //{C,M,D}
      begin
        linkSSM <= 1'b1;

        led <= 1'b1;
      end
      
      {B,T, D}: //{C,M,D}
      begin
        linkBTD <= 1'b1;
			 
        button_pull_done <= 1'b1;
	    button_rst_n <= 1'b1;
        

        led <= 1'b1;
      end
      			
      {T,P, T}: //{C,M,D}
      begin
        linkTPT <= 1'b1;

        led <= 1'b1;
      end
      			
      {S,S, S}: //{C,M,D}
      begin
        linkSSS <= 1'b1;

        led <= 1'b1;
      end
      			
      {T,P, W}: //{C,M,D}
      begin
        linkTPW <= 1'b1;

        led <= 1'b1;
      end
      			
      {T,O, C}: //{C,M,D}
      begin
        linkTOC <= 1'b1;

        led <= 1'b1;
      end
      			
      {F,I, U}: //{C,M,D}
      begin
        linkFIU <= 1'b1;

        led <= 1'b1;
      end
      			
      {S,P, M}: //{C,M,D}
      begin
        linkSPM <= 1'b1;

        led <= 1'b1;
      end
      			
      {T,S, P}: //{C,M,D}
      begin
        linkTSP <= 1'b1;

        led <= 1'b1;
      end
      			
      {T,I, C}: //{C,M,D}
      begin
        linkTIC <= 1'b1;

        led <= 1'b1;
      end
      
    /////////////////////////////////////////////

      {R,S,T}: //RESET
         begin
           			
        button_pull_done <= 1'b0;
	    button_rst_n <= 1'b0;
        
			linkBTU <= 1'b0;
			linkTDC <= 1'b0;
			linkSPS <= 1'b0;
			
        spi_slave_rst_b2b <= 1'b0;
        
			linkEMB <= 1'b0;
			linkFPM <= 1'b0;
			linkTCW <= 1'b0;
			linkGLO <= 1'b0;
			
        spi_rst <= 1'b0;
        spi_tx_en <= 1'b0;
        spi_rx_en <= 1'b0;
        mode_select_CPOL <= 1'b0;
        mode_select_CPHA <= 1'b0;
        
			linkDSS <= 1'b0;
			linkTCP <= 1'b0;
			linkSSM <= 1'b0;
			linkBTD <= 1'b0;
			linkTPT <= 1'b0;
			linkSSS <= 1'b0;
			linkTPW <= 1'b0;
			linkTOC <= 1'b0;
			linkFIU <= 1'b0;
			linkSPM <= 1'b0;
			linkTSP <= 1'b0;
			linkTIC <= 1'b0;

            led <= 1'b0;
            linkBIM <= 1'b1;
        end

         default:
         begin
          			
        button_pull_done <= 1'b0;
	    button_rst_n <= 1'b0;
        
			linkBTU <= 1'b0;
			linkTDC <= 1'b0;
			linkSPS <= 1'b0;
			
        spi_slave_rst_b2b <= 1'b0;
        
			linkEMB <= 1'b0;
			linkFPM <= 1'b0;
			linkTCW <= 1'b0;
			linkGLO <= 1'b0;
			
        spi_rst <= 1'b0;
        spi_tx_en <= 1'b0;
        spi_rx_en <= 1'b0;
        mode_select_CPOL <= 1'b0;
        mode_select_CPHA <= 1'b0;
        
			linkDSS <= 1'b0;
			linkTCP <= 1'b0;
			linkSSM <= 1'b0;
			linkBTD <= 1'b0;
			linkTPT <= 1'b0;
			linkSSS <= 1'b0;
			linkTPW <= 1'b0;
			linkTOC <= 1'b0;
			linkFIU <= 1'b0;
			linkSPM <= 1'b0;
			linkTSP <= 1'b0;
			linkTIC <= 1'b0;

          led <= 1'b0;
          linkBIM <= 1'b1;
      end
    endcase
  end
end


/////////////////////////////////////////////////////////////

endmodule
