//caution do not edit this file manually it is a template in tenjin format
`define  Buff_size 32
////////////////////////////////////////////
module top(clk,rst_n,rs232_rx, BusA,BusB, led);

///////////////////////////////////////////
input clk;	// 50MHz
input rst_n;	//reset, neg edge.
input rs232_rx;	// RS232 rec
//output rs232_tx;	//	RS232 transfer
/////////////////////////////////////////

inout [42:42] BusA;
inout [83:69] BusB;


////////////////////////////////////////
output led; // debug led

// state control						
parameter IDLE = 3'b000;
parameter S1 = 3'b001;
parameter WAIT = 3'b010;
parameter SAVE = 3'b100;

// commond reg
parameter A=8'h41 ;
parameter B=8'h42 ;
parameter C=8'h43 ;
parameter D=8'h44 ;
parameter E=8'h45 ;
parameter F=8'h46 ;
parameter G=8'h47 ;
parameter H=8'h48 ;
parameter I=8'h49 ;
parameter J=8'h4a ;
parameter K=8'h4b ;
parameter L=8'h4c ;
parameter M=8'h4d ;
parameter N=8'h4e ;
parameter O=8'h4f ;
parameter P=8'h50 ;
parameter Q=8'h51 ;
parameter R=8'h52 ;
parameter S=8'h53 ;
parameter T=8'h54 ;
parameter U=8'h55 ;
parameter V=8'h56 ;
parameter W=8'h57 ;
parameter X=8'h58 ;
parameter Y=8'h59 ;
parameter Z=8'h5a ;
parameter Z0=8'h30 ;
parameter I1=8'h31 ;
parameter II=8'h32 ;
parameter III=8'h33 ;
parameter IV=8'h34 ;
parameter V5=8'h35 ;
parameter VI=8'h36 ;
parameter VII=8'h37 ;
parameter VIII=8'h38 ;
parameter VIIII=8'h39 ;

//definition of inputs/outputs
wire test;
wire Flag; // signal the uart has data
wire rs232_rx;
wire clk,rst_n;
wire bps_start;	// start receive
wire bps_start_t;	// start tranmit
wire clk_bps;	//  uart bps
wire clk_bps_t;	//  uart bps
wire[7:0] rx_data; // receive data to parser
wire rx_int;       // receive interrupt

wire rx_error;
wire tx_error;

wire rx_complete;
wire tx_complete;
	
wire[7:0] tx_data;
wire rs232_tx;


wire sm_rd_sck;
wire sm_rd_mosi;
wire sm_rd_miso;
wire sm_rd_cs_n;
wire spi_receive_rd_status;
           
wire pha;
wire phb;
          



////////////////////////////////////////////////////////////////////////////////////////////////
//debug led
reg led;
reg cmd_red;																			
// settings for log register
reg [`Buff_size-1:0] Buff_temp;
reg [`Buff_size-9:0] Rx_cmd;											
reg [2:0] Current, Next;		
reg Flag_temp;
//build in module enable
reg linkBIM;
reg capture_rst;
reg linkUART;
reg linkTPM;
reg linkDSS;

reg spi_tx_rd_en;
reg spi_rx_rd_en;
reg spi_rd_rst;
reg mode_rd_select;
    reg linkDSM;
reg linkGII;
reg linkCMP;
 
reg enable_pwm_out;
reg[0:31] pwmfreq;
reg[0:31] dutyratio;
    

assign BusB[75] =  linkTPM ? BusB[73] : 1'bz;
assign BusB[83] =  linkDSS ? sm_rd_cs_n : 1'bz;
assign sm_rd_miso =  linkDSS ? BusB[77] : 1'bz;
assign BusB[69] =  linkDSS ? sm_rd_mosi : 1'bz;
assign BusB[73] =  linkDSS ? sm_rd_sck : 1'bz;
assign BusB[69] =  linkDSM ? BusB[77] : 1'bz;
assign BusA[42] =  linkGII ? BusB[81] : 1'bz;
assign BusA[42] =  linkCMP ? pha : 1'bz;


 
speed_select    speed_select( .clk(clk),  //baudrate selection
                      .rst_n(rst_n),
                      .rx_enable(bps_start),
                      .tx_enable(bps_start_t),
                      .buad_clk_rx(clk_bps),
                      .buad_clk_tx(clk_bps_t)
                      );

my_uart_rx      my_uart_rx(   .rst_n(rst_n), 
                      .baud_clk(clk_bps), 
                      .uart_rx(rs232_rx), 
                      .rx_data(rx_data),
                      .rx_enable(bps_start), 
                      .rx_complete(rx_complete), 
                      .rx_error(rx_error)
                      );
                      
my_uart_tx      my_uart_tx(   .rst_n(capture_rst), 
                      .baud_clk(clk_bps_t), 
                      .tx_start(led_tx_start & button_tx_start), 
                      .tx_data(tx_data), 
                      .tx_enable(bps_start_t), 
                      .tx_complete(tx_complete), 
                      .uart_tx(rs232_tx)
                      );
    
spi_ctrl_reduced      spi_ctrl_reduced_instance(
							.clk(clk),
							.rst_n(spi_rd_rst),
							.sck(sm_rd_sck),
							.mosi(sm_rd_mosi),
							.miso(sm_rd_miso),
							.cs_n(sm_rd_cs_n),
							.spi_tx_en(spi_tx_rd_en),
							.spi_rx_en(spi_rx_rd_en),
							.mode_select(mode_rd_select),
							.receive_status(spi_receive_rd_status)
							);
         
pwm_out pwm_out(.rst_n(rst_n),
          .clk(clk),
          .enable(enable_pwm_out),
          .pha(pha), 
          .phb(phb), 
          .pwmfre(pwmfreq), 
          .dutyratio(dutyratio)
        );
        

/////////////////////////////////////////////////////////////////////////////////////////////////////

reg flag_reg;
always @ (negedge bps_start or negedge rst_n)
begin
	if (!rst_n)
		flag_reg <= 1'b0;
	else if (!bps_start)
		flag_reg <= ~flag_reg;
end
assign Flag = flag_reg;

always @ (posedge clk or negedge rst_n)
begin
	if (!rst_n)
		Current <= IDLE;
	else
		Current <= Next;
end

// the state machine for receive data bytes
always @ (*)
begin
	Next = IDLE;
	case (Current)
		IDLE:
			if (rx_data == 8'h24) //$
				Next = S1;
			else
				Next = IDLE;
		S1:
			if (Flag_temp != Flag)
			begin
				if (rx_data != 8'h0d) //\n
					Next = S1;
				else
					Next = SAVE;
			end
			else
				Next = WAIT;
		WAIT:
			if (Flag_temp!=Flag)
			begin
				if (rx_data != 8'h0d)
					Next = S1;
				else
					Next = SAVE;
			end
			else
				Next = WAIT;
		default: Next = IDLE;
	endcase
end

always @ (posedge clk or negedge rst_n)
begin 
	if (!rst_n)
	begin
		Flag_temp <= 1'b0;
	end
	else
	begin
		Flag_temp <= Flag;
	end
end

always @ (posedge clk or negedge rst_n)
begin 
	if(!rst_n)
	begin
		Buff_temp <= `Buff_size'b0;
		Rx_cmd <= `Buff_size'b0;
		cmd_red <= 1'b0;
	end
	else
	begin
		case (Current)	
			IDLE:  
			begin
				Buff_temp <= `Buff_size'b0;
			end
			S1:
			begin
				cmd_red <= 1'b1;
				Buff_temp <= {{Buff_temp[`Buff_size - 9 : 0]}, rx_data};
			end 
			WAIT:
			begin
				Buff_temp <= Buff_temp;
			end 
			SAVE:
			begin
				Rx_cmd  <= Buff_temp[`Buff_size - 9 : 0];
				Buff_temp <= `Buff_size'b0;
				cmd_red <= 1'b0;
			end
			default: 
			begin
			end
		endcase		
	end	
end

always @ (posedge clk or negedge rst_n)
begin
  if(!rst_n)
  begin
    //////////////////add link here////////////////
			linkTPM <= 1'b0;
			linkDSS <= 1'b0;
			linkDSM <= 1'b0;
			linkGII <= 1'b0;
			linkCMP <= 1'b0;

    ///////////////////////////////////////////////
    led <= 1'b0; // for debug led
    linkBIM <= 1'b1;
  end
  else if(cmd_red) begin
						linkTPM <= 1'b0;
			
        spi_rd_rst <= 1'b0;
        spi_tx_rd_en <= 1'b0;
        spi_rx_rd_en <= 1'b0;
        mode_rd_select <= 1'b0;
        
			linkDSS <= 1'b0;
			linkDSM <= 1'b0;
			linkGII <= 1'b0;
			
    enable_pwm_out <= 1'b0;
    pwmfreq   <= 32'd500000;
    dutyratio <= 32'd250000;
    
			linkCMP <= 1'b0;

            led <= 1'b0;
            capture_rst <= 1'b0;
  end
  else
  begin
    case(Rx_cmd)
    ///////////////////add case here/////////////
      			
      {T,P, M}: //{C,M,D}
      begin
        linkTPM <= 1'b1;

        led <= 1'b1;
      end
      
      {D,S, S}: //{C,M,D}
      begin
        linkDSS <= 1'b1;
			 
        spi_rd_rst <= 1'b1;
        spi_tx_rd_en <= 1'b1;
        spi_rx_rd_en <= 1'b1;
        mode_rd_select <= 1'b0;
        

        led <= 1'b1;
      end
      			
      {D,S, M}: //{C,M,D}
      begin
        linkDSM <= 1'b1;

        led <= 1'b1;
      end
      			
      {G,I, I}: //{C,M,D}
      begin
        linkGII <= 1'b1;

        led <= 1'b1;
      end
      
      {C,M, P}: //{C,M,D}
      begin
        linkCMP <= 1'b1;
			 enable_pwm_out <= 1'b1;

        led <= 1'b1;
      end
      
    /////////////////////////////////////////////

      {R,S,T}: //RESET
         begin
           			linkTPM <= 1'b0;
			
        spi_rd_rst <= 1'b0;
        spi_tx_rd_en <= 1'b0;
        spi_rx_rd_en <= 1'b0;
        mode_rd_select <= 1'b0;
        
			linkDSS <= 1'b0;
			linkDSM <= 1'b0;
			linkGII <= 1'b0;
			
    enable_pwm_out <= 1'b0;
    pwmfreq   <= 32'd500000;
    dutyratio <= 32'd250000;
    
			linkCMP <= 1'b0;

            led <= 1'b0;
            linkBIM <= 1'b1;
            capture_rst <= 1'b0;
        end

         default:
         begin
          			linkTPM <= 1'b0;
			
        spi_rd_rst <= 1'b0;
        spi_tx_rd_en <= 1'b0;
        spi_rx_rd_en <= 1'b0;
        mode_rd_select <= 1'b0;
        
			linkDSS <= 1'b0;
			linkDSM <= 1'b0;
			linkGII <= 1'b0;
			
    enable_pwm_out <= 1'b0;
    pwmfreq   <= 32'd500000;
    dutyratio <= 32'd250000;
    
			linkCMP <= 1'b0;

          led <= 1'b0;
          linkBIM <= 1'b1;
          capture_rst <= 1'b0;		  
      end
    endcase
  end
end


/////////////////////////////////////////////////////////////

endmodule
